---
# Source: lgtm-distributed/charts/tempo/templates/configmap-runtime.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-tempo-runtime
  labels:
    helm.sh/chart: tempo-1.13.2
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.5.0"
    app.kubernetes.io/managed-by: Helm
  namespace: "lgtm"
data:
  overrides.yaml: |
    
    overrides: {}
