---
# Source: lgtm-distributed/charts/tempo/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-tempo
  namespace: lgtm
  labels:
    helm.sh/chart: tempo-1.13.2
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.5.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: false
