---
# Source: open-webui/charts/ollama/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-ollama
  namespace: openwebui
  labels:
    helm.sh/chart: ollama-1.16.0
    app.kubernetes.io/version: "0.6.8"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: open-webui-ollama
spec:
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/component: open-webui-ollama
  template:
    metadata:
      labels:
        helm.sh/chart: ollama-1.16.0
        app.kubernetes.io/version: "0.6.8"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/component: open-webui-ollama
    spec:
      serviceAccountName: open-webui-ollama
      securityContext:
        {}
      containers:
        - name: ollama
          securityContext:
            {}
          image: "ollama/ollama:0.6.8"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 11434
              protocol: TCP
          env:
            - name: OLLAMA_HOST
              value: "0.0.0.0:11434"
          envFrom:
          args:
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 6
      volumes:
        - name: ollama-data
          emptyDir: { }
