---
# Source: open-webui/charts/ollama/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-webui-ollama
  namespace: openwebui
  labels:
    helm.sh/chart: ollama-1.16.0
    app.kubernetes.io/version: "0.6.8"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: open-webui-ollama
automountServiceAccountToken: true
