---
# Source: kafka/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kafka-user-passwords
  namespace: "kafka"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    app.kubernetes.io/version: 3.8.0
    helm.sh/chart: kafka-30.1.3
type: Opaque
data:
  client-passwords: "QlNBUnlWMjEyNQ=="
  system-user-password: "QlNBUnlWMjEyNQ=="
  inter-broker-password: "aks0RTRBcGdNeg=="
  controller-password: "QVN0aDU1Uk5NZw=="
---
# Source: kafka/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kafka-kraft-cluster-id
  namespace: "kafka"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    app.kubernetes.io/version: 3.8.0
    helm.sh/chart: kafka-30.1.3
type: Opaque
data:
  kraft-cluster-id: "OWhaOUROWGhZSnFyR0RnaTlQSEdBVQ=="
