---
# Source: etcd/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: "etcd"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: etcd
    app.kubernetes.io/version: 3.5.15
    helm.sh/chart: etcd-10.2.8
    app.kubernetes.io/component: etcd
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: "client"
      port: 2379
      targetPort: client
      nodePort: null
    - name: "peer"
      port: 2380
      targetPort: peer
      nodePort: null
  selector:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/name: etcd
    app.kubernetes.io/component: etcd
