AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance with .env from Secrets Manager

Resources:

  # IAM Role for EC2 to access Secrets Manager
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: SecretAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: "*"

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: EC2InstanceRole

  # Secrets Manager Secret
  EnvSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: MyDotEnvSecret
      Description: .env configuration for EC2 app
      SecretString: |
        TEST_SECRET=vauleOfTestSecret

  # Security Group for EC2
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  # EC2 Instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      IamInstanceProfile: !Ref EC2InstanceProfile
      ImageId: ami-06c8f2ec674c67112  # Amazon Linux 2023 (update as needed for your region)
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          dnf update -y
          dnf install -y aws-cli jq git gcc-c++ make python3 python3-devel libffi-devel openssl-devel zlib-devel bzip2-devel readline-devel sqlite-devel wget golang

          export $(aws secretsmanager get-secret-value --secret-id MyDotEnvSecret | jq -r '.SecretString')
          echo "Startup script complete"
          # View logs at /var/log/cloud-init-output.log for AWS Linux 2023
Outputs:
  InstancePublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
