---
# Source: lgtm-distributed/charts/mimir/templates/ingester/ingester-pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: release-name-mimir-ingester
  labels:
    helm.sh/chart: mimir-5.3.0
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: ingester
    app.kubernetes.io/version: "2.12.0"
    app.kubernetes.io/managed-by: Helm
  namespace: "lgtm"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/component: ingester
  maxUnavailable: 1
