---
# Source: awx-operator/templates/clusterrole-awx-operator-metrics-reader.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    helm.sh/chart: awx-operator
  name: awx-operator-metrics-reader-release-name
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
