---
# Source: grafana-loki/templates/gateway/configmap-http.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-gateway
  namespace: "grafana-loki"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana-loki
    app.kubernetes.io/version: 1.27.0
    helm.sh/chart: grafana-loki-4.6.9
    app.kubernetes.io/part-of: grafana-loki
    app.kubernetes.io/component: gateway
data:
  nginx.conf: |+
      worker_processes  5;  ## Default: 1
      error_log  /dev/stderr;
      pid        /tmp/nginx.pid;
      worker_rlimit_nofile 8192;

      events {
        worker_connections  4096;  ## Default: 1024
      }

      http {
        client_body_temp_path /tmp/client_temp;
        proxy_temp_path       /tmp/proxy_temp_path;
        fastcgi_temp_path     /tmp/fastcgi_temp;
        uwsgi_temp_path       /tmp/uwsgi_temp;
        scgi_temp_path        /tmp/scgi_temp;

        default_type application/octet-stream;
        log_format  main '$remote_addr - $remote_user [$time_local]  $status ' '"$request" $body_bytes_sent "$http_referer" ' '"$http_user_agent" "$http_x_forwarded_for"';

        include /opt/bitnami/nginx/conf/resolvers.conf;

        map $status $loggable {
          ~^[23]  0;
          default 1;
        }
        access_log   /dev/stderr  main  if=$loggable;

        sendfile     on;
        tcp_nopush   on;

        server {
          listen             8080;

          location = / {
            return 200 'OK';
            auth_basic off;
          }

          location = /api/prom/push {
            proxy_pass       http://grafana-distributor.grafana-loki.svc.cluster.local:3100$request_uri;
          }

          location = /api/prom/tail {
            proxy_pass       http://grafana-querier.grafana-loki.svc.cluster.local:3100$request_uri;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
          }

          # Ruler
          location ~ /prometheus/api/v1/alerts.* {
            proxy_pass       http://grafana-ruler.grafana-loki.svc.cluster.local:3100$request_uri;
          }
          location ~ /prometheus/api/v1/rules.* {
            proxy_pass       http://grafana-ruler.grafana-loki.svc.cluster.local:3100$request_uri;
          }
          location ~ /api/prom/rules.* {
            proxy_pass       http://grafana-ruler.grafana-loki.svc.cluster.local:3100$request_uri;
          }
          location ~ /api/prom/alerts.* {
            proxy_pass       http://grafana-ruler.grafana-loki.svc.cluster.local:3100$request_uri;
          }

          location ~ /api/prom/.* {
            proxy_pass       http://grafana-query-frontend.grafana-loki.svc.cluster.local:3100$request_uri;
          }

          location = /loki/api/v1/push {
            proxy_pass       http://grafana-distributor.grafana-loki.svc.cluster.local:3100$request_uri;
          }

          location = /loki/api/v1/tail {
            proxy_pass       http://grafana-querier.grafana-loki.svc.cluster.local:3100$request_uri;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
          }

          location ~ /loki/api/.* {
            proxy_pass       http://grafana-query-frontend.grafana-loki.svc.cluster.local:3100$request_uri;
          }
        }
      }
