---
# Source: matomo/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: matomo-matomo
  labels:
    app.kubernetes.io/name: matomo
spec:
  
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"
