---
# Source: open-webui/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-webui
  namespace: openwebui
  labels:
    helm.sh/chart: open-webui-6.15.0
    app.kubernetes.io/version: "0.6.9"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: open-webui
automountServiceAccountToken: false
