apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-demo
  template:
    metadata:
      labels:
        app: maven-demo
    spec:
      containers:
        - name: maven-demo
          image: test
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Denv=prod"
---
apiVersion: v1
kind: Service
metadata:
  name: maven-demo-service
spec:
  selector:
    app: maven-demo
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
