---
# Source: grafana-mimir/charts/memcachedmetadata/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: release-name-memcachedmetadata
  namespace: grafana-mimir
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: memcachedmetadata
    app.kubernetes.io/version: 1.6.29
    helm.sh/chart: memcachedmetadata-7.4.10
