---
# Source: ingress/charts/controller/templates/admission-webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kong-controller-validation-webhook-ca-keypair
  namespace:  kong
  labels:
    app.kubernetes.io/name: controller
    helm.sh/chart: controller-2.48.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
type: kubernetes.io/tls
data:
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRYU5IU2lWWWFjSUpxcDBLelMwMDFLakFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOVEEwTVRFeE9UUTVNVGxhRncwegpOVEEwTURreE9UUTVNVGxhTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTNPM0QvWXZGV2ZVMTZMNW8xTWtYRjZFM1lDSFAKSHlHTDg1dDJQSEVReFFLWXJYYjcraE1JVlFpY0dNVlVCOHYrK1k0blZ4VzlOYzBuNnVNaG9wQzd1S1htWERiYgo5R1lJUGNpSHd3d3BRRFQ2cXpnbUlhTjVKblNvNk1NSjBzQWxYMnh5ZndJN0x2TXVrbVY2YklqR21VeDFHY1l6CmZhL0NDaktGV05jeTh1Y0R4eXdDSXA4aUdUWEdtNGNWV2tvYkRDcEtBVUtLY3hkK1E1S3QzVmdJS3BlcmlSZWQKdXZsY2FMSGlndFlPN0g2S3NFY01Tclc1UTJmYzBSVHZ1OVNyRjAxUFppaExERUJLUndCYkpuMlJkZWw5Q3FLQQpyMlhRZHlPWm9rM1pyZ1kwMnpETHEwYktnZHpJaWRIRkY0UDRYNlViNnkrZnUraytkZkRMZnJ6elJ3SURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZMbUx0RzdHb0hBZ2YxT3FCUTVpUDJ5aQowM29lTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDU2dHNGFsOFhjTW1wWWpJSFh1Z3JhUDExRmR4NXAxUmh0ClRmalQxZHViV3RTdU56eE95b2xreXRObjF2dXdDQUhBeHVXYUp1bzZpRkFveS9kUkhQVmMxM1ZoVlZhMXlaaUoKZTUySjJiNXhKV1FsaUtSUzR5L3JDUEZEQVlHdlhSbTRUL1B0ZTc4cjN6a3pMaEZITWd0RCtVaFRIV0JiUzhnbwo1QUNzM1NmWS9IbWc1ZFQ5NnBjUVhrNHFMNHk4UGJYSm5mTFMvckFnUUpXcWQ3cTJEV1ZqdnRIYTFYSllTbkRpClp6bTRLQ2JHeVllWUdvV1FCYUdYQVJnaklHd1ExT3ZqN0tIS0cvQVZZT0s0aEFLc2RZK0lIRXhybVoyTm5qSHIKdW9xSGNBRmgwSVYxZTJXK3hiUXluVDgvbSs1TlRBU2NFcCtQbkgyTWdPeFVzekFVSUFwYQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBM08zRC9ZdkZXZlUxNkw1bzFNa1hGNkUzWUNIUEh5R0w4NXQyUEhFUXhRS1lyWGI3CitoTUlWUWljR01WVUI4disrWTRuVnhXOU5jMG42dU1ob3BDN3VLWG1YRGJiOUdZSVBjaUh3d3dwUURUNnF6Z20KSWFONUpuU282TU1KMHNBbFgyeHlmd0k3THZNdWttVjZiSWpHbVV4MUdjWXpmYS9DQ2pLRldOY3k4dWNEeHl3QwpJcDhpR1RYR200Y1ZXa29iRENwS0FVS0tjeGQrUTVLdDNWZ0lLcGVyaVJlZHV2bGNhTEhpZ3RZTzdINktzRWNNClNyVzVRMmZjMFJUdnU5U3JGMDFQWmloTERFQktSd0JiSm4yUmRlbDlDcUtBcjJYUWR5T1pvazNacmdZMDJ6REwKcTBiS2dkeklpZEhGRjRQNFg2VWI2eStmdStrK2RmRExmcnp6UndJREFRQUJBb0lCQURmLy9NSHovOTVCalp5bApSeVZJbzVYVnc1ZVdlazNGenhlOHZFZXQwVFplNWh4eUlJVE85am0zcVBtT2F6SmV2dzY2dmJZUlNKaXVuQU9wCjl3aWg3ek5xdWUxOTZsc1UwZG4zVHBKZUxzYWJwejVuU1NNVnNNdlNuazRCd2lldGxNdVBUYVpzQmx4c1A4M1QKOHlnM3N6K0FaZDVXb3c2azBtYUxUOG1wSXJ6MjRTS25RQ01KWmZ2RDhlSmROc2liek4wcHBLOVk2QStlN3NieApOaFRBZkhJcXhZSUVzQ2Jid1RQSmY3eHVYMDNZTUR6cnRxQ09YYTFlYmNzUVdBS0swZG9HM3ljSWlGY05jb2NDCjlMS1lmQk41b2x4UE9IQ1hvRGMrNW15dzAzd0x2VFZuTzFqSk9XNzFxVWE3eTRLMUE3Qm84TXpXVWZDdUlTcS8KT0E0UythRUNnWUVBNkx2MFVHZDBPNkMvVE9mdERUMVpPZGhqUVh3Z1N4dEgvaVo4M1dXUHNEOFBPbnFvZXZiZgo5eE05RktmWkVlaUNPTmFCRllWL2F6Yjd0b21NZmJXeXoySGJZY2xiNTZISm50K25jWVpGN2xWTTg1dCt3ZjRyCjR2Q0dEYjY5bkEzdDlQWXJSaWxYZW90aEFoVEl3d2xLRmp0dE52MGxmNmR5UkNqY3lnd0ZkcnNDZ1lFQTh3T3cKOW96WnczQ2F3ZGxYTWFHOWNvb3BRekFxbEFmLzJrUnB3VlhXL3UzeTl0NlE0ZDBnbTJhc3FNZGFnTzB2a3UxLwo0ajFHbXdzd0gzbk0waVFyaDYxcm4xdjBwbjBzM0FoRnIwbldvZ1M1RElSaHZ0R0dtU2V6T0FBTnZkUGkyUjZXCnJXUEljWTRUV1llQzV0VXk4VWlUMklNcVlnMXZ2TFVBUEtxVVd1VUNnWUFOQnBnQitBaFZYZ1hXOUJRY2JaYVUKMmp1VDZyS1VBWTdoOXAxK2RyUzRGSTl4b25QVGpnV3krbXlzdjBneTdHUjljZVAvcEYwaFR3NS9oT3RNRGVOWQpJQTM3UngzUnRRaG56L1M3TWR5d0hpNFVaRnVQMS8zMDBhbHZFNEhoUGhaWFkzL0FpWWZQNEFVcDdLZmY0cUUyCjVWU1RnMCtaK1hFM3gyRzBIVUFoQ1FLQmdGMklKaXcrdWZIRy9VbHU1V2hzNEFXZHQ1UHNqZmE3dlhXOHJ4ZUMKZW1WVUlCZDBRajhzWk1ockZEbEJ3VXV0L29tR2I1b2NDM2pSTFl4dnpLMTB6bXhDQ3hJaXlsN3Avc0lSVFFEUwpZcEdwVDYvSm8vVlZuNENERHkrV2xiTmlRZ1ZmQ0k5andGbzBYSzR3d2VrbVZaMFlXZzhUTE5UZ1p3a3lnUXpZCmVwRWhBb0dBU0tvRXF2T3cvWll0elFNVTJnc3luc0RVZDcrVlZJdXRITG9SK2g3OVh5MlViRFBVK3hqOFdnQzAKeVJBNGRtSmtCMHVMcXZnTjhNbWNUNzRMckYvOG5ZVndxck80YlNNUkFLb2NzTk1XSnJEMGhBNEhKQVBJcDZnSgprU0xEYUhMbDR0UXdUWVoweTZUSFlqZ1p2VDJtVDc2TFlTUllNUWpjMTdFNU8zMmdvMWM9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
# Source: ingress/charts/controller/templates/admission-webhook.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kong-controller-validation-webhook-keypair
  namespace:  kong
  labels:
    app.kubernetes.io/name: controller
    helm.sh/chart: controller-2.48.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkekNDQWwrZ0F3SUJBZ0lSQUo1SFlwMGxzdTUvaVlkOXA4M1NQc2d3RFFZSktvWklodmNOQVFFTEJRQXcKSERFYU1CZ0dBMVVFQXhNUmEyOXVaeTFoWkcxcGMzTnBiMjR0WTJFd0hoY05NalV3TkRFeE1UazBPVEU1V2hjTgpNelV3TkRBNU1UazBPVEU1V2pBMk1UUXdNZ1lEVlFRREV5dHJiMjVuTFdOdmJuUnliMnhzWlhJdGRtRnNhV1JoCmRHbHZiaTEzWldKb2IyOXJMbXR2Ym1jdWMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUIKQ2dLQ0FRRUEybUw4U3AzOGRMNVRrMHAvNk9tb2dQaFdmQnFmaGdQWVFpVXp5bE5ScThTY3Vsa1JKVldVZllBWgowQ3BvbUZjSWg0QTlsVU56b2FydG1rMEwzNTZrUUluTWZpRTQ0RXZCMVA4L0s5dlJReDZuUGJRcjlwbTRHTGVCCjJGYzlDanl4SmVVdE4wOVh5TFVNM2pmVDg5cEtza0QvdkxneTZQVlRlUWRRY1VSczJrbmh3R3gyeVBpV1VZU3oKL0ZVNFZXQytrWkQvSUkvMDZLTnEvTURBSzVWYm1JUWtWZHRrTmVPSGsxNGRveWJraWtLUlpPdTJGajkwb2NjOQo2TXFFNHVucFdVSVl3MFdCbzVEbkt5TllDUm00OW91U0MwakMyd21IMFR4cG9GaUpzZkJRWUUrUXJBYUxKbk5hCk5IRlZFTEtoSU04MWJocDI0WTRLMjJMNzlpTms5UUlEQVFBQm80R1pNSUdXTUE0R0ExVWREd0VCL3dRRUF3SUYKb0RBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEQVlEVlIwVEFRSC9CQUl3QURBZgpCZ05WSFNNRUdEQVdnQlM1aTdSdXhxQndJSDlUcWdVT1lqOXNvdE42SGpBMkJnTlZIUkVFTHpBdGdpdHJiMjVuCkxXTnZiblJ5YjJ4c1pYSXRkbUZzYVdSaGRHbHZiaTEzWldKb2IyOXJMbXR2Ym1jdWMzWmpNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBTDhuRVphTXpucThTMG5CODgrdkpHRG1XSDllWUdzektKbGcrT3dsNkpyWEkvOWZOTgovSVU1T0dUOTZacmwwVTArRy80c1BVMGE1SSs0V3U3WTlDWmF3RG5HM2lTbmtHK3lqUGtiNWYvdFp4dlNMQjQ2CkNIQ3dES0NFL0xrcHhjYUlHNlNOVFU0TnIrQ2hjc0dRbklJUHRrTFJYc3NZZnZpc1EwOSthc2V0bEo2V3VpWFAKNEtrS1p0bDY4d3B1cFhNNTlWZkRNa0pOMUFZTGRjcFpBYVdZVWg2V0xTVFd1US9EeHFsSVk4MG4zbXJSd1FvaAplNzBRNy84T012Zmh5ejAzTjlla3J6cit0YTZablBGRXZDVjZRa1daL0RnMzZFdmxLdy9xTWJFd0tMZjducUI3Cjd4cUVGME80bldHRkJvL1VNMkc4UFlwcVZCR3ljTXFkUWFTTgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBMm1MOFNwMzhkTDVUazBwLzZPbW9nUGhXZkJxZmhnUFlRaVV6eWxOUnE4U2N1bGtSCkpWV1VmWUFaMENwb21GY0loNEE5bFVOem9hcnRtazBMMzU2a1FJbk1maUU0NEV2QjFQOC9LOXZSUXg2blBiUXIKOXBtNEdMZUIyRmM5Q2p5eEplVXROMDlYeUxVTTNqZlQ4OXBLc2tEL3ZMZ3k2UFZUZVFkUWNVUnMya25od0d4Mgp5UGlXVVlTei9GVTRWV0Mra1pEL0lJLzA2S05xL01EQUs1VmJtSVFrVmR0a05lT0hrMTRkb3lia2lrS1JaT3UyCkZqOTBvY2M5Nk1xRTR1bnBXVUlZdzBXQm81RG5LeU5ZQ1JtNDlvdVNDMGpDMndtSDBUeHBvRmlKc2ZCUVlFK1EKckFhTEpuTmFOSEZWRUxLaElNODFiaHAyNFk0SzIyTDc5aU5rOVFJREFRQUJBb0lCQUU1SnlmUGQ2eERXNGhNZApVL2xsT2pqeHpkOHpsQmh3N0dmWitsVC94WGwwUkZNeGRzb1JnZWZ6c2sxRHhyZEdEQkszVUZ4Z0QrWFc1dEszCjZCZkVRVkc1bEl0cTBYN202WmUzNFNlUjU5VE4rbHBPYXF3K3N4WjVRcDBSdVJvZ1k4a1gvVHVrdisxOXFoMUgKbWo0QzlXQXRtUUJJY0VlL0dxdDZpY1h4SjZ5Z3dpRlB5ZVZjTE5pTGszUDRPSzNnTjZ2ck5ZSFVmQ1NnYkN4ZgoyWFJqajBzVHJXbFpJV3YxYVkwVVlKNDYzeGY0WnU4RmZ5d2hDbGRta3F5c05IZFVoSGxDc2FRY0RqRUsvTm1ICjkvTEtEbzRBZWVKMC9UdzJzWWlWbXdlYnl0Zm9yU01QclMzc2ZaVWs4MitpUmlISm84Y0JidXNMcVBmZXl6WUcKZE5GdG1va0NnWUVBNUVRazhObmpsSDRjSlF4MjYwK2I0dDFrVHUrUWhJOVI5Q0dEcFdGd21BUVhsRDZrSkIxQgo3LzRxVjhxRlB2NlF2bEVDcXhqZUt4RUR2d3NmR05QTlZoYnd5NUlkcnVDUkFTM0RmS01ROTRsUnd4NGlEOW81CmxFMjdtbStjVXFKL0tWdkFIUkRlZDYrVUYwbHNnbVdyU1Ura0ZxS0JxcDBaZHF4L0xEZDduTDhDZ1lFQTlPdU4KNXBnZ3hlTkUzSnlKUjdRN2V6bkJPL1dHZlRkaGM1UXNFSVhLVTh3dVo0dC9ESndaRy9KcEt5SHRHY2QvNHlySgp2eEZYQkpDT3ZBQy9GcTRPdlN0RkZuWW5wVW83bktFcEFwNEtxS0Exc05JQ2RnNng4Zjc5azhxeFA1V2x0SXNJCjdBbVZrWVNTNzhzL2czTlp2eEIybklOQ29Ra2R2cHJWVDJMc3gwc0NnWUFISWhvRmJNbXYya0VHNTF6UC9hemgKYWdtNGJjUVdZR1F2UE56Z1RpczJsT29udDgxcFU0QzcvelZUaVFDZzkxT09udmwyWDFDU0IvWVdBa0wyZzZmbgpDTkI5akJOaFk2TWtaa20xbTJMc1dWNDB1cnhWd253S0ptTzJiOFp5enFFcXFiTlhOUysramI0Uy9EaG4yc1YvCmhQMmJ0M2hWM0pMdkluVFc3T1R3QVFLQmdITjdJWlJKeEtJcHo4MUpqYjBlY1RGZ0FRbTVjZWxXbEg5L3JPczUKZWpYYXYwS1pWcFZtZ0x4WnAxYnNEelNwaVZaZVZYUGV4QzNsenpjOER0MnR3a3RWdktTam4zdmpMWXBqdnNkNgpKMEp0RUFQSWNkcWlnU3ErZFdnYkdVb0cwSFA1WG9LVTNrNFh1WVNSUytnNkdtWHBhRlBSM0RlNzZhZDJyLzlYCmdKZFRBb0dBZVZyL3ZtTnpRU2xUN3RwR3drRGR3QnYrVDluMEd4cS95M2o0S24wSVdBdFRHUXFXQ2RDMnR0VWYKSlZNSmpzQm1OUmsrTk9DemNQS3hQbEtLVEdzcVFZK2pMMkhnSHFVMWc5UWs2Vk1GWTAzYWpLd3gyMzVKdlRIQwpCaEI3bG1YV0VnWXhEQ0tsUElNdGR5K242bExRRVY0bFU4NklvbnRUWU0rc2xLMVBSU289Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
# Source: ingress/charts/controller/templates/admission-webhook.yaml
apiVersion: v1
kind: Service
metadata:
  name: kong-controller-validation-webhook
  namespace: kong
  labels:
    app.kubernetes.io/name: controller
    helm.sh/chart: controller-2.48.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
spec:
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: webhook
  selector:
    app.kubernetes.io/name: controller
    helm.sh/chart: controller-2.48.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
    app.kubernetes.io/component: app
---
# Source: ingress/charts/controller/templates/admission-webhook.yaml
kind: ValidatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: kong-controller-kong-validations
  labels:
    app.kubernetes.io/name: controller
    helm.sh/chart: controller-2.48.0
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/managed-by: "Helm"
    
    app.kubernetes.io/version: "3.9"
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRYU5IU2lWWWFjSUpxcDBLelMwMDFLakFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOVEEwTVRFeE9UUTVNVGxhRncwegpOVEEwTURreE9UUTVNVGxhTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTNPM0QvWXZGV2ZVMTZMNW8xTWtYRjZFM1lDSFAKSHlHTDg1dDJQSEVReFFLWXJYYjcraE1JVlFpY0dNVlVCOHYrK1k0blZ4VzlOYzBuNnVNaG9wQzd1S1htWERiYgo5R1lJUGNpSHd3d3BRRFQ2cXpnbUlhTjVKblNvNk1NSjBzQWxYMnh5ZndJN0x2TXVrbVY2YklqR21VeDFHY1l6CmZhL0NDaktGV05jeTh1Y0R4eXdDSXA4aUdUWEdtNGNWV2tvYkRDcEtBVUtLY3hkK1E1S3QzVmdJS3BlcmlSZWQKdXZsY2FMSGlndFlPN0g2S3NFY01Tclc1UTJmYzBSVHZ1OVNyRjAxUFppaExERUJLUndCYkpuMlJkZWw5Q3FLQQpyMlhRZHlPWm9rM1pyZ1kwMnpETHEwYktnZHpJaWRIRkY0UDRYNlViNnkrZnUraytkZkRMZnJ6elJ3SURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZMbUx0RzdHb0hBZ2YxT3FCUTVpUDJ5aQowM29lTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDU2dHNGFsOFhjTW1wWWpJSFh1Z3JhUDExRmR4NXAxUmh0ClRmalQxZHViV3RTdU56eE95b2xreXRObjF2dXdDQUhBeHVXYUp1bzZpRkFveS9kUkhQVmMxM1ZoVlZhMXlaaUoKZTUySjJiNXhKV1FsaUtSUzR5L3JDUEZEQVlHdlhSbTRUL1B0ZTc4cjN6a3pMaEZITWd0RCtVaFRIV0JiUzhnbwo1QUNzM1NmWS9IbWc1ZFQ5NnBjUVhrNHFMNHk4UGJYSm5mTFMvckFnUUpXcWQ3cTJEV1ZqdnRIYTFYSllTbkRpClp6bTRLQ2JHeVllWUdvV1FCYUdYQVJnaklHd1ExT3ZqN0tIS0cvQVZZT0s0aEFLc2RZK0lIRXhybVoyTm5qSHIKdW9xSGNBRmgwSVYxZTJXK3hiUXluVDgvbSs1TlRBU2NFcCtQbkgyTWdPeFVzekFVSUFwYQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-controller-validation-webhook
      namespace: kong
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: secrets.credentials.validation.ingress-controller.konghq.com
  objectSelector:
    matchExpressions:
    - key: "konghq.com/credential"
      operator: "Exists"
    - key: "konghq.com/credential"
      operator: "NotIn"
      values:
      - "konnect"
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - secrets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRYU5IU2lWWWFjSUpxcDBLelMwMDFLakFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOVEEwTVRFeE9UUTVNVGxhRncwegpOVEEwTURreE9UUTVNVGxhTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTNPM0QvWXZGV2ZVMTZMNW8xTWtYRjZFM1lDSFAKSHlHTDg1dDJQSEVReFFLWXJYYjcraE1JVlFpY0dNVlVCOHYrK1k0blZ4VzlOYzBuNnVNaG9wQzd1S1htWERiYgo5R1lJUGNpSHd3d3BRRFQ2cXpnbUlhTjVKblNvNk1NSjBzQWxYMnh5ZndJN0x2TXVrbVY2YklqR21VeDFHY1l6CmZhL0NDaktGV05jeTh1Y0R4eXdDSXA4aUdUWEdtNGNWV2tvYkRDcEtBVUtLY3hkK1E1S3QzVmdJS3BlcmlSZWQKdXZsY2FMSGlndFlPN0g2S3NFY01Tclc1UTJmYzBSVHZ1OVNyRjAxUFppaExERUJLUndCYkpuMlJkZWw5Q3FLQQpyMlhRZHlPWm9rM1pyZ1kwMnpETHEwYktnZHpJaWRIRkY0UDRYNlViNnkrZnUraytkZkRMZnJ6elJ3SURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZMbUx0RzdHb0hBZ2YxT3FCUTVpUDJ5aQowM29lTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDU2dHNGFsOFhjTW1wWWpJSFh1Z3JhUDExRmR4NXAxUmh0ClRmalQxZHViV3RTdU56eE95b2xreXRObjF2dXdDQUhBeHVXYUp1bzZpRkFveS9kUkhQVmMxM1ZoVlZhMXlaaUoKZTUySjJiNXhKV1FsaUtSUzR5L3JDUEZEQVlHdlhSbTRUL1B0ZTc4cjN6a3pMaEZITWd0RCtVaFRIV0JiUzhnbwo1QUNzM1NmWS9IbWc1ZFQ5NnBjUVhrNHFMNHk4UGJYSm5mTFMvckFnUUpXcWQ3cTJEV1ZqdnRIYTFYSllTbkRpClp6bTRLQ2JHeVllWUdvV1FCYUdYQVJnaklHd1ExT3ZqN0tIS0cvQVZZT0s0aEFLc2RZK0lIRXhybVoyTm5qSHIKdW9xSGNBRmgwSVYxZTJXK3hiUXluVDgvbSs1TlRBU2NFcCtQbkgyTWdPeFVzekFVSUFwYQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-controller-validation-webhook
      namespace: kong
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: secrets.plugins.validation.ingress-controller.konghq.com
  objectSelector:
    matchExpressions:
    - key: owner
      operator: NotIn
      values:
      - helm
    - key: "konghq.com/credential"
      operator: "NotIn"
      values:
      - "konnect"
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - secrets
  sideEffects: None
- name: validations.kong.konghq.com
  matchPolicy: Equivalent
  objectSelector:
    matchExpressions:
    - key: owner
      operator: NotIn
      values:
      - helm
  failurePolicy: Ignore
  sideEffects: None
  admissionReviewVersions: ["v1beta1"]
  rules:
  - apiGroups:
    - configuration.konghq.com
    apiVersions:
    - '*'
    operations:
    - CREATE
    - UPDATE
    resources:
    - kongconsumers
    - kongplugins
    - kongclusterplugins
    - kongingresses
  - apiGroups:
    - ''
    apiVersions:
    - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - services
  - apiGroups:
    - networking.k8s.io
    apiVersions:
      - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - ingresses
  - apiGroups:
    - gateway.networking.k8s.io
    apiVersions:
    - 'v1alpha2'
    - 'v1beta1'
    - 'v1'
    operations:
    - CREATE
    - UPDATE
    resources:
    - gateways
    - httproutes
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJekNDQWd1Z0F3SUJBZ0lRYU5IU2lWWWFjSUpxcDBLelMwMDFLakFOQmdrcWhraUc5dzBCQVFzRkFEQWMKTVJvd0dBWURWUVFERXhGcmIyNW5MV0ZrYldsemMybHZiaTFqWVRBZUZ3MHlOVEEwTVRFeE9UUTVNVGxhRncwegpOVEEwTURreE9UUTVNVGxhTUJ3eEdqQVlCZ05WQkFNVEVXdHZibWN0WVdSdGFYTnphVzl1TFdOaE1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTNPM0QvWXZGV2ZVMTZMNW8xTWtYRjZFM1lDSFAKSHlHTDg1dDJQSEVReFFLWXJYYjcraE1JVlFpY0dNVlVCOHYrK1k0blZ4VzlOYzBuNnVNaG9wQzd1S1htWERiYgo5R1lJUGNpSHd3d3BRRFQ2cXpnbUlhTjVKblNvNk1NSjBzQWxYMnh5ZndJN0x2TXVrbVY2YklqR21VeDFHY1l6CmZhL0NDaktGV05jeTh1Y0R4eXdDSXA4aUdUWEdtNGNWV2tvYkRDcEtBVUtLY3hkK1E1S3QzVmdJS3BlcmlSZWQKdXZsY2FMSGlndFlPN0g2S3NFY01Tclc1UTJmYzBSVHZ1OVNyRjAxUFppaExERUJLUndCYkpuMlJkZWw5Q3FLQQpyMlhRZHlPWm9rM1pyZ1kwMnpETHEwYktnZHpJaWRIRkY0UDRYNlViNnkrZnUraytkZkRMZnJ6elJ3SURBUUFCCm8yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FxUXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZMbUx0RzdHb0hBZ2YxT3FCUTVpUDJ5aQowM29lTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDU2dHNGFsOFhjTW1wWWpJSFh1Z3JhUDExRmR4NXAxUmh0ClRmalQxZHViV3RTdU56eE95b2xreXRObjF2dXdDQUhBeHVXYUp1bzZpRkFveS9kUkhQVmMxM1ZoVlZhMXlaaUoKZTUySjJiNXhKV1FsaUtSUzR5L3JDUEZEQVlHdlhSbTRUL1B0ZTc4cjN6a3pMaEZITWd0RCtVaFRIV0JiUzhnbwo1QUNzM1NmWS9IbWc1ZFQ5NnBjUVhrNHFMNHk4UGJYSm5mTFMvckFnUUpXcWQ3cTJEV1ZqdnRIYTFYSllTbkRpClp6bTRLQ2JHeVllWUdvV1FCYUdYQVJnaklHd1ExT3ZqN0tIS0cvQVZZT0s0aEFLc2RZK0lIRXhybVoyTm5qSHIKdW9xSGNBRmgwSVYxZTJXK3hiUXluVDgvbSs1TlRBU2NFcCtQbkgyTWdPeFVzekFVSUFwYQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kong-controller-validation-webhook
      namespace: kong
