---
# Source: odoo/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: odoo
  namespace: "odoo"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: odoo
    app.kubernetes.io/version: 17.0.20240905
    helm.sh/chart: odoo-26.2.18
type: Opaque
data:
  odoo-password: "RVRGcm1iQ0FmRQ=="
