apiVersion: v1
kind: Pod
metadata:
  name: hello-world-2
  namespace: my-first-namespace
  labels:
    app: hello-world-2
spec:
  containers:
  - name: hello-world-2
    image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
    ports:
    - containerPort: 8080