---
# Source: grafana-mimir/charts/memcachedindex/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: release-name-memcachedindex
  namespace: grafana-mimir
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: memcachedindex
    app.kubernetes.io/version: 1.6.29
    helm.sh/chart: memcachedindex-7.4.10
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: memcachedindex
