---
# Source: grafana-mimir/charts/memcachedindex/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: release-name-memcachedindex
  namespace: grafana-mimir
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: memcachedindex
    app.kubernetes.io/version: 1.6.29
    helm.sh/chart: memcachedindex-7.4.10
