---
# Source: awx-operator/templates/serviceaccount-awx-operator-controller-manager.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: awx-operator
  name: awx-operator-controller-manager
