---
# Source: lgtm-distributed/charts/loki/templates/querier/service-querier.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-loki-querier
  namespace: lgtm
  labels:
    helm.sh/chart: loki-0.79.0
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.9.6"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: querier
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: querier
