apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka:3.7.0
          command:
            - sh
            - -c
            - |
              export PATH=$PATH:/opt/kafka/bin && \
              /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties \
              --override broker.id=1 \
              --override zookeeper.connect=zookeeper:2181 \
              --override log.dirs=/tmp/kafka-logs \
              --override listeners=PLAINTEXT://:9092 \
              --override advertised.listeners=PLAINTEXT://kafka:9092 \
              --override listener.security.protocol.map=PLAINTEXT:PLAINTEXT \
              --override offsets.topic.replication.factor=1
          ports:
            - containerPort: 9092
