---
# Source: airflow/templates/statsd/statsd-serviceaccount.yaml
######################################
## Airflow StatsD ServiceAccount
######################################
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: "airflow-statsd"
  labels:
    tier: airflow
    component: statsd
    release: airflow
    chart: "airflow-1.16.0"
    heritage: Helm
