---
# Source: airflow/templates/statsd/statsd-service.yaml
################################
## Airflow StatsD Service
#################################
apiVersion: v1
kind: Service
metadata:
  name: airflow-statsd
  labels:
    tier: airflow
    component: statsd
    release: airflow
    chart: "airflow-1.16.0"
    heritage: Helm
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9102"
spec:
  type: ClusterIP
  selector:
    tier: airflow
    component: statsd
    release: airflow
  ports:
    - name: statsd-ingest
      protocol: UDP
      port: 9125
      targetPort: 9125
    - name: statsd-scrape
      protocol: TCP
      port: 9102
      targetPort: 9102
