---
# Source: postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: "postgresql"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.2.0
    helm.sh/chart: postgresql-16.3.5
type: Opaque
data:
  postgres-password: "RXFiSGdpNno4Tg=="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
