---
# Source: fluent-bit/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: fluent-bit
  labels:
    helm.sh/chart: fluent-bit-0.49.0
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "4.0.1"
    app.kubernetes.io/managed-by: Helm
