---
# Source: grafana-mimir/charts/minio/templates/provisioning-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-minio-provisioning
  namespace: "grafana-mimir"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: minio
    app.kubernetes.io/version: 2024.7.16
    helm.sh/chart: minio-14.6.27
    app.kubernetes.io/component: minio-provisioning
data:
