---
# Source: fluent-bit/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: monitoring
  labels:
    helm.sh/chart: fluent-bit-0.47.5
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "3.1.4"
    app.kubernetes.io/managed-by: Helm
