---
# Source: airflow/templates/redis/redis-serviceaccount.yaml
######################################
## Airflow Redis ServiceAccount
######################################
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: "airflow-redis"
  labels:
    tier: airflow
    component: redis
    release: airflow
    chart: "airflow-1.16.0"
    heritage: Helm
