---
# Source: grafana-loki/charts/memcachedfrontend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-memcachedfrontend
  namespace: grafana-loki
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: memcachedfrontend
    app.kubernetes.io/version: 1.6.29
    helm.sh/chart: memcachedfrontend-7.4.10
spec:
  type: ClusterIP
  ports:
    - name: memcache
      port: 11211
      targetPort: memcache
      nodePort: null
  selector:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/name: memcachedfrontend
