---
# Source: grafana-loki/charts/memcachedchunks/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: release-name-memcachedchunks
  namespace: grafana-loki
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: memcachedchunks
    app.kubernetes.io/version: 1.6.29
    helm.sh/chart: memcachedchunks-7.4.10
