FROM clickhouse/clickhouse-server
COPY configs/server_settings/settings.xml /etc/clickhouse-server/config.d/server.xml
COPY configs/user_settings/settings.xml /etc/clickhouse-server/config.d/user.xml
COPY configs/client_settings/settings.xml /etc/clickhouse-client/config.d/client.xml