---
# Source: clearml/templates/apiserver-asyncdelete-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clearml-apiserver-asyncdelete
  labels:
    helm.sh/chart: clearml-7.14.6
    app.kubernetes.io/name: clearml
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: clearml
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: clearml
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: clearml-apiserver
      securityContext:
        
        {}
      initContainers:
        - name: init-apiserver
          image: "docker.io/allegroai/clearml:2.0.0-613"
          command:
            - /bin/sh
            - -c
            - >
              set -x;
              while [ $(curl -sw '%{http_code}' "http://clearml-elastic-master:9200/_cluster/health" -o /dev/null) -ne 200 ] ; do
                echo "waiting for elasticsearch" ;
                sleep 5 ;
              done ;
              while [ $(curl --telnet-option BOGUS --connect-timeout 2 -s "telnet://release-name-mongodb:27017" -o /dev/null; echo $?) -ne 49 ] ; do
                echo "waiting for mongodb" ;
                sleep 5 ;
              done ;
              while [ $(curl --telnet-option BOGUS --connect-timeout 2 -s "telnet://release-name-redis-master:6379" -o /dev/null; echo $?) -ne 49 ] ; do
                echo "waiting for redis" ;
                sleep 5 ;
              done ;
          securityContext:
            
            {}
          resources:
            limits:
              cpu: 10m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 64Mi
      containers:
        - name: clearml-apiserver
          image: "docker.io/allegroai/clearml:2.0.0-613"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - >
              python3 -m jobs.async_urls_delete --fileserver-host http://clearml-fileserver:8081
          env:
          - name: CLEARML_REDIS_SERVICE_HOST
            value: release-name-redis-master
          - name: CLEARML_REDIS_SERVICE_PORT
            value: "6379"
          - name: CLEARML_MONGODB_SERVICE_CONNECTION_STRING
            value: "mongodb://release-name-mongodb:27017"
          - name: CLEARML__HOSTS__ELASTIC__WORKERS__HOSTS
            value: "[{\"host\":\"clearml-elastic-master\",\"port\":9200,\"scheme\":\"\"}]"
          - name: CLEARML__HOSTS__ELASTIC__EVENTS__HOSTS
            value: "[{\"host\":\"clearml-elastic-master\",\"port\":9200,\"scheme\":\"\"}]"
          - name: CLEARML__HOSTS__ELASTIC__DATASETS__HOSTS
            value: "[{\"host\":\"clearml-elastic-master\",\"port\":9200,\"scheme\":\"\"}]"
          - name: CLEARML__HOSTS__ELASTIC__LOGS__HOSTS
            value: "[{\"host\":\"clearml-elastic-master\",\"port\":9200,\"scheme\":\"\"}]"
          - name: CLEARML__secure__auth__token_secret
            valueFrom:
              secretKeyRef:
                name: "clearml-conf"
                key: secure_auth_token_secret
          - name: CLEARML__apiserver__default_company_name
            value: "d1bd92a3b039400cbafc60a7a5b1e52b"
          - name: CLEARML__logging__handlers__text_file__filename
            value: "/dev/null"
          - name: PYTHONPATH
            value: /opt/clearml/apiserver
          - name: CLEARML__apiserver__default_company
            value: ""
          - name: CLEARML__services__async_urls_delete__fileserver__url_prefixes
            value: "[\"http://clearml-fileserver:8081\"]"
          resources:
            limits:
              cpu: 2000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext:
            
            {}
