---
# Source: clearml/templates/fileserver-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: clearml-fileserver
  labels:
    helm.sh/chart: clearml-7.14.6
    app.kubernetes.io/name: clearml
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
      protocol: TCP
  selector:
    app.kubernetes.io/name: clearml
    app.kubernetes.io/instance: clearml-fileserver
