---
# Source: lgtm-distributed/charts/loki/templates/runtime-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-loki-runtime
  namespace: lgtm
  labels:
    helm.sh/chart: loki-0.79.0
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.9.6"
    app.kubernetes.io/managed-by: Helm
data:
  runtime.yaml: |
    
    {}
