---
# Source: lgtm-distributed/charts/tempo/templates/compactor/service-compactor.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-tempo-compactor
  labels:
    helm.sh/chart: tempo-1.13.2
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: compactor
    app.kubernetes.io/version: "2.5.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 3100
      targetPort: 3100
      protocol: TCP
  selector:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: compactor
