---
# Source: open-webui/charts/pipelines/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-webui-pipelines
  namespace: openwebui
  labels:
    helm.sh/chart: pipelines-0.6.0
    app.kubernetes.io/version: "alpha"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: open-webui-pipelines
