---
# Source: grafana-mimir/charts/memcachedchunks/templates/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: release-name-memcachedchunks
  namespace: "grafana-mimir"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: memcachedchunks
    app.kubernetes.io/version: 1.6.29
    helm.sh/chart: memcachedchunks-7.4.10
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: memcachedchunks
      app.kubernetes.io/version: 1.6.29
      helm.sh/chart: memcachedchunks-7.4.10
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - ports:
        - port: 11211
