---
# Source: airflow/templates/triggerer/triggerer-serviceaccount.yaml
################################
## Airflow Triggerer ServiceAccount
#################################
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: "airflow-triggerer"
  labels:
    tier: airflow
    component: triggerer
    release: airflow
    chart: "airflow-1.16.0"
    heritage: Helm
