---
# Source: airflow/templates/secrets/metadata-connection-secret.yaml
################################
## Airflow Metadata Secret
#################################
apiVersion: v1
kind: Secret
metadata:
  name: airflow-metadata
  labels:
    tier: airflow
    release: airflow
    chart: airflow
    heritage: Helm
type: Opaque
data:
  connection: "cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQGFpcmZsb3ctcG9zdGdyZXNxbC5haXJmbG93OjU0MzIvcG9zdGdyZXM/c3NsbW9kZT1kaXNhYmxl"
