---
# Source: airflow/templates/secrets/webserver-secret-key-secret.yaml
############################################
## Airflow Webserver Flask Secret Key Secret
############################################

apiVersion: v1
kind: Secret
metadata:
  name: airflow-webserver-secret-key
  labels:
    tier: airflow
    component: webserver
    release: airflow
    chart: airflow
    heritage: Helm
type: Opaque
data:
  webserver-secret-key: "YzI0ZTBhZWQ5OTk2NWNmMGM0Y2JlNjZhOGQxZDc5ZDM="
