---
# Source: airflow/templates/jobs/migrate-database-job-serviceaccount.yaml
#############################################
## Airflow Migrate Database Job ServiceAccount
##############################################
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: "airflow-migrate-database-job"
  labels:
    tier: airflow
    component: run-airflow-migrations
    release: airflow
    chart: "airflow-1.16.0"
    heritage: Helm
