---
# Source: grafana-tempo/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: "grafana-tempo"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana-tempo
    app.kubernetes.io/version: 2.5.0
    helm.sh/chart: grafana-tempo-3.7.4
    app.kubernetes.io/component: tempo
automountServiceAccountToken: false
