---
# Source: grafana-tempo/templates/tempo-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-tempo
  namespace: "grafana-tempo"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana-tempo
    app.kubernetes.io/version: 2.5.0
    helm.sh/chart: grafana-tempo-3.7.4
    app.kubernetes.io/component: tempo
data:
  tempo.yaml: |-
    multitenancy_enabled: false
    cache:
      caches:
        - memcached:
            host: release-name-memcached
            service: memcache
            timeout: 500ms
            consistent_hash: true
          roles:
            - bloom
            - trace-id-index
    compactor:
      compaction:
        block_retention: 48h
      ring:
        kvstore:
          store: memberlist
    distributor:
      ring:
        kvstore:
          store: memberlist
      receivers:
        jaeger:
          protocols:
            thrift_http:
              endpoint: 0.0.0.0:14268
            grpc:
              endpoint: 0.0.0.0:14250
    querier:
      frontend_worker:
        frontend_address: grafana-query-frontend-headless:9095
    ingester:
      lifecycler:
        ring:
          replication_factor: 1
          kvstore:
            store: memberlist
        tokens_file_path: /bitnami/grafana-tempo/data/tokens.json
    metrics_generator:
      ring:
        kvstore:
          store: memberlist
      storage:
        path: /bitnami/grafana-tempo/data/wal
        remote_write: 
          []
    memberlist:
      bind_port: 7946
      abort_if_cluster_join_fails: false
      join_members:
        - grafana-gossip-ring:7946
    overrides:
      per_tenant_override_config: /bitnami/grafana-tempo/conf/overrides.yaml
    server:
      http_listen_port: 3200
      grpc_listen_port: 9095
    storage:
      trace:
        backend: local
        blocklist_poll: 5m
        local:
          path: /bitnami/grafana-tempo/data/traces
        wal:
          path: /bitnami/grafana-tempo/data/wal
