---
# Source: clearml/charts/elasticsearch/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "clearml-elastic-master"
  annotations:
  labels:
    heritage: "Helm"
    release: "release-name"
    chart: "elasticsearch-7.17.3"
    app: "clearml-elastic-master"
