apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vector
  template:
    metadata:
      labels:
        app: vector
    spec:
      containers:
      # --- Debug Sidecar Container ---
      - name: debugger
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c", "sleep infinity"]
      # --- Main Vector Container ---
      - name: vector
        image: timberio/vector:0.34.1-distroless-static
        args: ["--config", "/etc/vector/vector.yaml"]
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: vector-env
        volumeMounts:
            - name: config
              mountPath: /etc/vector/vector.yaml
              subPath: vector.yaml
      volumes:
        - name: vector-env
          secret:
            secretName: vector-env
        - name: config
          configMap:
            name: vector-config
---
apiVersion: v1
kind: Service
metadata:
  name: vector
spec:
  selector:
    app: vector
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer