apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:latest
          ports:
            - containerPort: 9042
      volumes:
        - name: config-volume
          configMap:
            name: cassandra-config
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  type: NodePort
  ports:
    - port: 9042
      targetPort: 9042
  selector:
    app: cassandra
