---
# Source: grafana-tempo/templates/query-frontend/query-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-query-frontend
  namespace: "grafana-tempo"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana-tempo
    app.kubernetes.io/version: 2.5.0
    helm.sh/chart: grafana-tempo-3.7.4
    app.kubernetes.io/component: query
data:
  tempo-query.yaml: |-
    backend: 127.0.0.1:3200
