---
# Source: airflow/templates/rbac/pod-log-reader-rolebinding.yaml
################################
## Airflow Pod Reader Role Binding
#################################
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "airflow"
  name: airflow-pod-log-reader-rolebinding
  labels:
    tier: airflow
    release: airflow
    chart: "airflow-1.16.0"
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-pod-log-reader-role
subjects:
  - kind: ServiceAccount
    name: "airflow-webserver"
    namespace: "airflow"
  - kind: ServiceAccount
    name: "airflow-triggerer"
    namespace: "airflow"
