---
# Source: airflow/templates/rbac/pod-launcher-rolebinding.yaml
################################
## Airflow Pod Launcher Role Binding
#################################
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "airflow"
  name: airflow-pod-launcher-rolebinding
  labels:
    tier: airflow
    release: airflow
    chart: "airflow-1.16.0"
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-pod-launcher-role
subjects:
  - kind: ServiceAccount
    name: "airflow-worker"
    namespace: "airflow"
