---
# Source: jenkins/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: "jenkins"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/version: 2.462.3
    helm.sh/chart: jenkins-13.4.23
automountServiceAccountToken: false
