---
# Source: gateway-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: gateway-operator
    helm.sh/chart: gateway-operator-0.5.4
    app.kubernetes.io/instance: "kong"
    app.kubernetes.io/version: "1.5"
    app.kubernetes.io/component: kgo
  name: kong-controller-manager
  namespace:  kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-operator
      app.kubernetes.io/component: kgo
      app.kubernetes.io/instance: "kong"
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: gateway-operator
        helm.sh/chart: gateway-operator-0.5.4
        app.kubernetes.io/instance: "kong"
        app.kubernetes.io/version: "1.5"
        app.kubernetes.io/component: kgo
        app: kong
        version: "1.5"
    spec:
      containers:
      - name: manager
        env:        
        - name: GATEWAY_OPERATOR_KONG_ADMIN_URL
          value: "https://localhost:8444"
        - name: GATEWAY_OPERATOR_HEALTH_PROBE_BIND_ADDRESS
          value: ":8081"
        - name: GATEWAY_OPERATOR_METRICS_BIND_ADDRESS
          value: "0.0.0.0:8080"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "docker.io/kong/gateway-operator:1.5"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        ports:
        - containerPort: 8081
          name: probe
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
        volumeMounts:
        - name: kong-certs-dir
          mountPath: /tmp/k8s-webhook-server/serving-certs
      securityContext:
        runAsNonRoot: true
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: kong-certs-dir
        emptyDir:
          sizeLimit: 256Mi
