---
# Source: grafana-mimir/templates/mimir-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: "grafana-mimir"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana-mimir
    app.kubernetes.io/version: 2.13.0
    helm.sh/chart: grafana-mimir-1.2.10
    app.kubernetes.io/part-of: grafana-mimir
    app.kubernetes.io/component: mimir
data:
  mimir.yaml: |-
    activity_tracker:
      filepath: /bitnami/grafana-mimir/activity.log
    alertmanager_storage:
      backend: s3
      s3:
        access_key_id: ${MIMIR_MINIO_ACCESS_KEY_ID}
        bucket_name: alertmanager
        endpoint: release-name-minio:80
        insecure: true
        secret_access_key: ${MIMIR_MINIO_SECRET_ACCESS_KEY}
    api:
      alertmanager_http_prefix: /alertmanager
      prometheus_http_prefix: /prometheus
    blocks_storage:
      backend: s3
      bucket_store:
        chunks_cache:
          backend: memcached
          memcached:
            addresses: release-name-memcachedchunks:11211
            timeout: 450ms
        index_cache:
          backend: memcached
          memcached:
            addresses: release-name-memcachedindex:11211
            timeout: 450ms
        metadata_cache:
          backend: memcached
          memcached:
            addresses: release-name-memcachedmetadata:11211
            timeout: 450ms
        sync_dir: /bitnami/grafana-mimir/tsdb-sync
      s3:
        access_key_id: ${MIMIR_MINIO_ACCESS_KEY_ID}
        bucket_name: mimir
        endpoint: release-name-minio:80
        insecure: true
        secret_access_key: ${MIMIR_MINIO_SECRET_ACCESS_KEY}
      tsdb:
        dir: /bitnami/grafana-mimir/tsdb
    compactor:
      data_dir: /bitnami/grafana-mimir/compactor
    frontend:
      cache_results: true
      parallelize_shardable_queries: true
      results_cache:
        backend: memcached
        memcached:
          addresses: release-name-memcachedfrontend:11211
          timeout: 500ms
    frontend_worker:
      frontend_address: grafana-query-frontend-headless.grafana-mimir.svc:9095
      grpc_client_config:
        max_send_msg_size: 419430400
    ingester:
      ring:
        final_sleep: 0s
        num_tokens: 512
        tokens_file_path: /bitnami/grafana-mimir/tokens
        unregister_on_shutdown: false
    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
    limits:
      max_cache_freshness: 10m
      max_query_parallelism: 240
      max_total_query_length: 12000h
    memberlist:
      abort_if_cluster_join_fails: false
      advertise_port: 7946
      bind_port: 7946
      compression_enabled: false
      join_members:
      - dns+grafana-gossip-ring.grafana-mimir.svc.cluster.local:7946
    querier:
      max_concurrent: 16
    query_scheduler:
      max_outstanding_requests_per_tenant: 800
    server:
      grpc_listen_port: 9095
      grpc_server_max_concurrent_streams: 1000
      grpc_server_max_connection_age: 2m
      grpc_server_max_connection_age_grace: 5m
      grpc_server_max_connection_idle: 1m
      http_listen_port: 8080
    store_gateway:
      sharding_ring:
        tokens_file_path: /bitnami/grafana-mimir/tokens
        wait_stability_min_duration: 1m
    usage_stats:
      installation_mode: helm
