---
# Source: grafana-mimir/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: "grafana-mimir"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana-mimir
    app.kubernetes.io/version: 2.13.0
    helm.sh/chart: grafana-mimir-1.2.10
    app.kubernetes.io/part-of: grafana-mimir
    app.kubernetes.io/component: mimir
automountServiceAccountToken: false
